# Generated by Django 4.0.3 on 2022-03-08 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetDetails',
            new_name='PetDetail',
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name': 'sex', 'verbose_name_plural': 'Sexes'},
        ),
    ]
