# Generated by Django 4.0.3 on 2022-03-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_remove_sex_sex_remove_petdetail_pet_petdetail_pet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet',
            new_name='PetInfo',
        ),
    ]
