# Generated by Django 4.0.3 on 2022-03-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_rename_pet_petinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='petinfo',
            name='sex',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet.sex'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='petdetail',
            name='pet',
        ),
        migrations.AddField(
            model_name='petdetail',
            name='pet',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet.petinfo'),
            preserve_default=False,
        ),
    ]
