# Generated by Django 4.0.3 on 2022-03-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_petinfo_sex_remove_petdetail_pet_petdetail_pet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petinfo',
            options={'verbose_name': 'petinfo', 'verbose_name_plural': 'petinfo'},
        ),
        migrations.AddField(
            model_name='petdetail',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
