# Generated by Django 4.0.3 on 2022-03-09 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_alter_petinfo_options_petdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinfo',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.sex'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
