# Generated by Django 4.0.3 on 2022-03-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_petinfo_sex_alter_sex_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name': 'sex', 'verbose_name_plural': 'Sex'},
        ),
        migrations.AddField(
            model_name='petinfo',
            name='breed',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petinfo',
            name='color',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petinfo',
            name='country_of_origin',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petinfo',
            name='description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petinfo',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/pet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petinfo',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PetDetail',
        ),
    ]
